# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ddaf9bb74d6577a47dd422b073f45daf30449e2efd623cf0406ab70a5f1cd6db7273e992c39a158e47e77accc2557f51af6fcd850ef7f3e3b6db39e1c3c514ea

test:
  secret_key_base: ba23cedb345719076ecb626b8e4be0658cec5a308e507ae20567c30363674de13e072fb2b3c547b0a89b461ef23f00ae0d1bab4353c90ee063e953d587b1231d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
